appVersion: 1.7.2
description: A popular open source ecommerce solution. Professional tools are easily
  accessible to increase online sales including instant guest checkout, abandoned
  cart reminders and automated Email marketing.
engine: gotpl
home: https://prestashop.com/
icon: https://bitnami.com/assets/stacks/prestashop/img/prestashop-stack-110x117.png
keywords:
- prestashop
- e-commerce
- http
- web
- php
maintainers:
- email: containers@bitnami.com
  name: bitnami-bot
name: prestashop
sources:
- https://github.com/bitnami/bitnami-docker-prestashop
version: 0.5.3
