description: free, fully compatible, enhanced, open source drop-in replacement for
  MySQL
engine: gotpl
home: https://www.percona.com/
icon: https://www.percona.com/sites/all/themes/percona2015/logo.png
keywords:
- mysql
- percona
- database
- sql
maintainers:
- email: patg@patg.net
  name: Patrick Galbraith
name: percona
sources:
- https://github.com/kubernetes/charts
- https://github.com/docker-library/percona
version: 0.3.0
