appVersion: 1.9.16
description: Web-based test management system that facilitates software quality assurance.
engine: gotpl
home: http://www.testlink.org/
icon: https://bitnami.com/assets/stacks/testlink/img/testlink-stack-220x234.png
keywords:
- testlink
- testing
- http
- php
maintainers:
- email: containers@bitnami.com
  name: bitnami-bot
name: testlink
sources:
- https://github.com/bitnami/bitnami-docker-testlink
version: 0.5.0
