apiVersion: v1
appVersion: 0.4.0
description: Kubed by AppsCode - Kubernetes daemon
home: https://github.com/appscode/kubed
icon: https://cdn.appscode.com/images/icon/kubed.png
maintainers:
- email: support@appscode.com
  name: appscode
name: kubed
sources:
- https://github.com/appscode/kubed
version: 0.3.0
