apiVersion: v1
appVersion: 1.1.0
description: Scales worker nodes within autoscaling groups.
engine: gotpl
icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
maintainers:
- email: mgoodness@gmail.com
  name: Michael Goodness
name: cluster-autoscaler
sources:
- https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler
- https://github.com/spotinst/kubernetes-autoscaler/tree/master/cluster-autoscaler
version: 0.5.0
