apiVersion: v1
description: Heapster enables Container Cluster Monitoring and Performance Analysis.
engine: gotpl
keywords:
- metrics
- cadvisor
- monitoring
maintainers:
- email: jose.g.aguirre@intel.com
  name: Jose Aguirre
name: heapster
sources:
- https://github.com/kubernetes/heapster
- https://github.com/kubernetes/contrib/tree/master/addon-resizer
version: 0.2.7
