appVersion: 0.2.3
description: A Helm chart for cert-manager
home: https://github.com/jetstack/cert-manager
keywords:
- cert-manager
- kube-lego
- letsencrypt
- tls
maintainers:
- email: james@jetstack.io
  name: munnerz
name: cert-manager
sources:
- https://github.com/jetstack/cert-manager
version: 0.2.3
