description: DokuWiki is a standards-compliant, simple to use wiki optimized for creating
  documentation. It is targeted at developer teams, workgroups, and small companies.
  All data is stored in plain text files, so no database is required.
engine: gotpl
home: http://www.dokuwiki.org/
icon: https://bitnami.com/assets/stacks/dokuwiki/img/dokuwiki-stack-110x117.png
keywords:
- dokuwiki
- wiki
- php
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: dokuwiki
sources:
- https://github.com/bitnami/bitnami-docker-dokuwiki
version: 0.2.2
