apiVersion: v1
appVersion: 1.0.0
description: Risk Advisor add-on module for Kubernetes
home: https://www.riskadvisory.net/
icon: https://raw.githubusercontent.com/Prytu/risk-advisor/master/logo.svg
maintainers:
- email: pawel.poskrobko@icloud.com
  name: pposkrobko
- email: mich.pryt@gmail.com
  name: Prytu
- email: graczykowskimichal@gmail.com
  name: GraczykowskiMichal
- email: jacek.maksymowicz@student.uw.edu.pl
  name: jackmax
name: risk-advisor
sources:
- https://github.com/Prytu/risk-advisor/
version: 2.0.3
