appVersion: 3.4.1
description: Moodle is a learning platform designed to provide educators, administrators
  and learners with a single robust, secure and integrated system to create personalised
  learning environments
engine: gotpl
home: http://www.moodle.org/
icon: https://bitnami.com/assets/stacks/moodle/img/moodle-stack-110x117.png
keywords:
- moodle
- learning
- php
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: moodle
sources:
- https://github.com/bitnami/bitnami-docker-moodle
version: 0.5.0
