apiVersion: v1
appVersion: "2.2"
description: A reverse proxy that provides authentication with Google, Github or other
  providers
engine: gotpl
keywords:
- kubernetes
- oauth
- oauth2
- authentication
- google
- github
maintainers:
- email: casey@monax.io
  name: compleatang
name: oauth2-proxy
sources:
- https://github.com/bitly/oauth2_proxy
version: 0.2.0
