apiVersion: v1
appVersion: 5.9.1
description: Universal Repository Manager supporting all major packaging formats,
  build tools and CI servers.
home: https://www.jfrog.com/artifactory/
icon: https://raw.githubusercontent.com/JFrogDev/artifactory-dcos/master/images/jfrog_med.png
keywords:
- artifactory
- jfrog
maintainers:
- email: jainishs@jfrog.com
  name: jainishshah17
- email: eldada@jfrog.com
  name: eldada
name: artifactory-ha
sources:
- https://bintray.com/jfrog/product/JFrog-Artifactory-Pro/view
- https://github.com/JFrogDev
version: 0.1.1
