appVersion: 1.1.5
description: CockroachDB is a scalable, survivable, strongly-consistent SQL database.
home: https://www.cockroachlabs.com
icon: https://raw.githubusercontent.com/cockroachdb/cockroach/master/docs/media/cockroach_db.png
maintainers:
- email: alex@cockroachlabs.com
  name: Alex Robinson
name: cockroachdb
sources:
- https://github.com/cockroachdb/cockroach
version: 0.6.6
