apiVersion: v1
appVersion: 0.6.2
description: Stash by AppsCode - Backup your Kubernetes Volumes
home: https://github.com/appscode/stash
icon: https://cdn.appscode.com/images/icon/stash.png
maintainers:
- email: support@appscode.com
  name: appscode
name: stash
sources:
- https://github.com/appscode/stash
version: 0.4.0
