appVersion: 6.4.2
description: The JasperReports server can be used as a stand-alone or embedded reporting
  and BI server that offers web-based reporting, analytic tools and visualization,
  and a dashboard feature for compiling multiple custom views
engine: gotpl
home: http://community.jaspersoft.com/project/jasperreports-server
icon: https://bitnami.com/assets/stacks/jasperserver/img/jasperserver-stack-110x117.png
keywords:
- business intelligence
- java
- jasper
- reporting
- analytic
- visualization
maintainers:
- email: containers@bitnami.com
  name: bitnami-bot
name: jasperreports
sources:
- https://github.com/bitnami/bitnami-docker-jasperreports
version: 0.2.5
