apiVersion: v1
appVersion: "1"
description: A Helm chart for GCP Night King
home: https://hub.docker.com/r/itamarost/gcp-night-king/
maintainers:
- email: itamarost@gmail.com
  name: itamaro
name: gcp-night-king
sources:
- https://github.com/itamaro/gcp-go-night-king
- https://github.com/itamaro/gcp-night-king
version: 1.0.0
