apiVersion: v1
appVersion: 2.7.3
description: The Apache Hadoop software library is a framework that allows for the
  distributed processing of large data sets across clusters of computers using simple
  programming models.
home: https://hadoop.apache.org/
icon: http://hadoop.apache.org/images/hadoop-logo.jpg
maintainers:
- email: disla@google.com
  name: danisla
name: hadoop
sources:
- https://github.com/apache/hadoop
version: 1.0.4
