appVersion: 3.8.5
description: PHP content management system (CMS) for publishing web content
engine: gotpl
home: http://www.joomla.org/
icon: https://bitnami.com/assets/stacks/joomla/img/joomla-stack-220x234.png
keywords:
- joomla
- cms
- blog
- http
- php
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: joomla
sources:
- https://github.com/bitnami/bitnami-docker-joomla
version: 0.5.7
