appVersion: 3.11.0
description: Chart for selenium grid
engine: gotpl
home: http://www.seleniumhq.org/
icon: http://docs.seleniumhq.org/images/big-logo.png
keywords:
- qa
maintainers:
- email: techops@adaptly.com
  name: flah00
- email: diemol@gmail.com
  name: diemol
name: selenium
sources:
- https://github.com/SeleniumHQ/docker-selenium
version: 0.2.7
