description: Collect information about Kubernetes clusters to help improve the project.
engine: gotpl
maintainers:
- email: mgoodness@gmail.com
  name: Michael Goodness
name: spartakus
sources:
- https://github.com/kubernetes-incubator/spartakus
version: 1.1.3
