apiVersion: v1
deprecated: true
description: Scales worker nodes within autoscaling groups.
engine: gotpl
icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
maintainers:
- email: mgoodness@gmail.com
  name: Michael Goodness
name: aws-cluster-autoscaler
sources:
- https://github.com/kubernetes/contrib/tree/master/cluster-autoscaler/cloudprovider/aws
version: 0.3.2
