apiVersion: v1
appVersion: v0.2.0
description: Kanister-operator Helm chart for Kubernetes
home: https://kanister.io/
icon: https://kasten.io/assets/img/kanister-logo.png
maintainers:
- email: ilya@kasten.io
  name: depohmel
- email: tom@kasten.io
  name: tdmanv
name: kanister-operator
version: 0.2.1
