appVersion: 2.2.3
description: A feature-rich flexible e-commerce solution. It includes transaction
  options, multi-store functionality, loyalty programs, product categorization and
  shopper filtering, promotion rules, and more.
engine: gotpl
home: https://magento.com/
icon: https://bitnami.com/assets/stacks/magento/img/magento-stack-110x117.png
keywords:
- magento
- e-commerce
- http
- web
- php
maintainers:
- email: containers@bitnami.com
  name: bitnami-bot
name: magento
sources:
- https://github.com/bitnami/bitnami-docker-magento
version: 0.6.4
