appVersion: 0.17.4
description: Distributed computation in Python with task scheduling
home: https://dask.pydata.org
icon: https://avatars3.githubusercontent.com/u/17131925?v=3&s=200
maintainers:
- email: df.rodriguez143@gmail.com
  name: danielfrg
- email: mrocklin@gmail.com
  name: mrocklin
name: dask
sources:
- https://github.com/dask/dask
version: 1.0.4
