apiVersion: v1
description: Dashboard for the Sensu monitoring framework
engine: gotpl
home: https://uchiwa.io/
icon: https://uchiwa.io/img/favicon.png
keywords:
- uchiwa
- sensu
- monitoring
maintainers:
- email: shane.starcher@gmail.com
  name: Shane Starcher
name: uchiwa
sources:
- https://github.com/kubernetes/charts
- https://github.com/sstarcher/docker-uchiwa
- https://github.com/sensu/uchiwa
version: 0.2.3
