apiVersion: v1
appVersion: 1.6.7
description: |
  Pachyderm is a large-scale container-based workflow engine that offers complete version control for data and reproducible data processing
home: https://pachyderm.io
icon: https://avatars2.githubusercontent.com/u/10432478?s=200
keywords:
- pachyderm
- workflows
- reproducibility
- distributed
- processing
maintainers:
- email: novella.uu@gmail.com
  name: jonandernovella
- email: whitenack.daniel@gmail.com
  name: dwhitena
- email: jdoliner@pachyderm.io
  name: jdoliner
name: pachyderm
sources:
- https://github.com/pachyderm/pachyderm
version: 0.1.5
