apiVersion: v1
description: A micro application development and integration platform that enables
  organizations to create and deliver secure micro applications that tie into existing
  business systems and track changes to key business data.
engine: gotpl
home: http://www.sapho.com
icon: https://www.sapho.com/wp-content/uploads/2016/04/sapho-logotype.svg
maintainers:
- email: support@sapho.com
  name: Sapho
name: sapho
sources:
- https://bitbucket.org/sapho/ops-docker-tomcat/src
- https://hub.docker.com/r/sapho/ops-docker-tomcat
- https://github.com/kubernetes/charts/tree/master/stable/mysql
version: 0.2.1
