apiVersion: v1
appVersion: 1.7.3
description: Centrifugo is a real-time messaging server.
home: https://github.com/centrifugal/centrifugo
icon: https://avatars3.githubusercontent.com/u/6236442
keywords:
- centrifugo
- websocket
- golang
maintainers:
- email: ozimok.oleg@gmail.com
  name: oleh-ozimok
name: centrifugo
version: 2.0.0
