appVersion: 18.2.0
description: GoCD is an open-source continuous delivery server to model and visualize
  complex workflows with ease.
home: https://www.gocd.org/
icon: https://gocd.github.io/assets/images/go-icon-black-192x192.png
keywords:
- gocd
- ci
- cd
- ci/cd
- continuous-integration
- continuous-delivery
- continuous-deployment
- continuous-testing
maintainers:
- email: arvind@thoughtworks.com
  name: arvindsv
- email: ganeshpl@thoughtworks.com
  name: ganeshspatil
- email: varshasvaradarajan@gmail.com
  name: varshavaradarajan
name: gocd
sources:
- https://github.com/gocd/gocd
version: 1.0.0
