appVersion: 3.3.2
description: Concourse is a simple and scalable CI system.
engine: gotpl
home: https://concourse.ci/
icon: https://avatars1.githubusercontent.com/u/7809479
keywords:
- ci
- concourse
- concourse.ci
maintainers:
- email: frodenas@gmail.com
  name: frodenas
- email: viglesias@google.com
  name: viglesiasce
name: concourse
sources:
- https://github.com/concourse/bin
- https://github.com/kubernetes/charts
version: 0.4.0
