apiVersion: v1
appVersion: v0.27.2
description: The easy, open source way for everyone in your company to ask questions
  and learn from data.
home: http://www.metabase.com/
icon: http://www.metabase.com/images/logo.svg
maintainers:
- email: phamminhthanh69@gmail.com
  name: pmint93
name: metabase
sources:
- https://github.com/metabase/metabase
version: 0.3.2
